server:
  port: 8011
spring:
  application:
    name: dataplatfrom-eureka
  security:
    user:
      name: admin
      password: admin
eureka:
  server:
    enable-self-preservation: false # 设置为false表示关闭保护模式
    eviction-interval-timer-in-ms: 60000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  instance: 
    hostname: localhost
  client:
    registerWithEureka: false # 当前的微服务不注册到eureka之中
    fetchRegistry: false   # 不通过eureka获取注册信息
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/