language: node_js

git:
  depth: false

branches:
  only:
    - master

node_js:
  - node

cache: yarn

install: yarn

script: yarn build:docs

deploy:
  provider: pages
  repo: vuepress/vuepress.github.io
  target-branch: master
  github-token: $GITHUB_TOKEN
  local-dir: packages/docs/dist
  skip-cleanup: true
  keep_history: false
  on:
    branch: master
