package otc.tech.model;

import javax.persistence.*;

@Table(name = "TAB_BUSINESS_RULES")
public class BusinessRules {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer rId;
	
    private String rKey;// 标识

    private String rName;// 名称

    private String rType;// 类型

    private String rContent;// 规则

    private String remark;// 提示信息

    
    public String getrKey() {
        return rKey;
    }

    public Integer getrId() {
		return rId;
	}

	public void setrId(Integer rId) {
		this.rId = rId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAB_BUSINESS_RULES.R_KEY
     *
     * @param rKey the value for TAB_BUSINESS_RULES.R_KEY
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public void setrKey(String rKey) {
        this.rKey = rKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAB_BUSINESS_RULES.R_NAME
     *
     * @return the value of TAB_BUSINESS_RULES.R_NAME
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAB_BUSINESS_RULES.R_NAME
     *
     * @param rName the value for TAB_BUSINESS_RULES.R_NAME
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAB_BUSINESS_RULES.R_TYPE
     *
     * @return the value of TAB_BUSINESS_RULES.R_TYPE
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public String getrType() {
        return rType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAB_BUSINESS_RULES.R_TYPE
     *
     * @param rType the value for TAB_BUSINESS_RULES.R_TYPE
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public void setrType(String rType) {
        this.rType = rType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAB_BUSINESS_RULES.R_CONTENT
     *
     * @return the value of TAB_BUSINESS_RULES.R_CONTENT
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public String getrContent() {
        return rContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAB_BUSINESS_RULES.R_CONTENT
     *
     * @param rContent the value for TAB_BUSINESS_RULES.R_CONTENT
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public void setrContent(String rContent) {
        this.rContent = rContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAB_BUSINESS_RULES.REMARK
     *
     * @return the value of TAB_BUSINESS_RULES.REMARK
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAB_BUSINESS_RULES.REMARK
     *
     * @param remark the value for TAB_BUSINESS_RULES.REMARK
     *
     * @mbg.generated Tue Aug 27 16:50:23 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}