package otc.tech.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

@Table(name = "TAB_REPORT_TYPES")
public class ReportTypes {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer typeId;// 主键

	private String typeCodeInterface;// 报告类型编码（对应数据接口）

	private String typeName;// 报告名称

	private String remark;// 备注

	private String tTemplateType;// 关联模板
	@Transient
	private String dIsDqbg;// 是否定期报告，0|否、1|是
	@Transient
	private String typeCode;// 报告类型代码（对应报告库）
	@Transient
	private String reportType;// 报告类型（没使用字段）

	// private Set<Template> templateElements = new HashSet<>(); // 模板要素

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.type_code
	 *
	 * @return the value of TAB_REPORT_TYPES.type_code
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.type_code
	 *
	 * @param typeCode
	 *            the value for TAB_REPORT_TYPES.type_code
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public Integer getTypeId() {
		return typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.type_code_interface
	 *
	 * @return the value of TAB_REPORT_TYPES.type_code_interface
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getTypeCodeInterface() {
		return typeCodeInterface;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.type_code_interface
	 *
	 * @param typeCodeInterface
	 *            the value for TAB_REPORT_TYPES.type_code_interface
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setTypeCodeInterface(String typeCodeInterface) {
		this.typeCodeInterface = typeCodeInterface;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.type_name
	 *
	 * @return the value of TAB_REPORT_TYPES.type_name
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.type_name
	 *
	 * @param typeName
	 *            the value for TAB_REPORT_TYPES.type_name
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.remark
	 *
	 * @return the value of TAB_REPORT_TYPES.remark
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.remark
	 *
	 * @param remark
	 *            the value for TAB_REPORT_TYPES.remark
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.d_is_dqbg
	 *
	 * @return the value of TAB_REPORT_TYPES.d_is_dqbg
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getdIsDqbg() {
		return dIsDqbg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.d_is_dqbg
	 *
	 * @param dIsDqbg
	 *            the value for TAB_REPORT_TYPES.d_is_dqbg
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setdIsDqbg(String dIsDqbg) {
		this.dIsDqbg = dIsDqbg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.t_template_type
	 *
	 * @return the value of TAB_REPORT_TYPES.t_template_type
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String gettTemplateType() {
		return tTemplateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.t_template_type
	 *
	 * @param tTemplateType
	 *            the value for TAB_REPORT_TYPES.t_template_type
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void settTemplateType(String tTemplateType) {
		this.tTemplateType = tTemplateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column TAB_REPORT_TYPES.report_type
	 *
	 * @return the value of TAB_REPORT_TYPES.report_type
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public String getReportType() {
		return reportType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column TAB_REPORT_TYPES.report_type
	 *
	 * @param reportType
	 *            the value for TAB_REPORT_TYPES.report_type
	 *
	 * @mbg.generated Tue Aug 27 16:59:09 CST 2019
	 */
	public void setReportType(String reportType) {
		this.reportType = reportType;
	}
}